server:
  port: 8101
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      enabled: true
      routes: 
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path= /users/**
        - id: ORDER-Service
          uri: lb://ORDER-SERVICE
          predicates:
          - Path= /orders/**