server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://loacalhost:8010/eureka/
    
  instance:
    hostname: localhost
    